# Generated by Django 5.2.11 on 2026-04-22 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('points_earned', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='clubs.club')),
            ],
        ),
    ]
