# Generated by Django 5.2.11 on 2026-04-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_points_clubpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
    ]
