# Generated by Django 5.2.11 on 2026-05-04 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_club_logo_url_club_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('max_attendees', models.IntegerField(default=50)),
                ('points_to_earn', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clubs.club')),
                ('participants', models.ManyToManyField(blank=True, related_name='registered_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
