# Generated by Django 5.2.11 on 2026-05-06 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('WORKSHOPS', 'Workshops'), ('DISCUSSIONS', 'Discussions'), ('EXHIBITIONS', 'Exhibitions'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='attended_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
