# Generated by Django 5.2.11 on 2026-05-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_activity_category_activity_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.CharField(blank=True, choices=[('events', 'Events'), ('media', 'Media'), ('design', 'Design'), ('content', 'Content'), ('projects', 'Projects'), ('management', 'Management')], max_length=30, null=True),
        ),
    ]
